# Site settings
author: Jon Harwood
title: 11/26 Online Software Engineering 
header-img: img/home-bg.png
email: jhharwood88@gmail.com
copyright_name: Jon Harwood
description: > # this means to ignore newlines until "baseurl:"
  Full time cohort
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jhharwood88

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
